networkPolicy:
  enabled: true
  ingress:
    ingressController:
      enabled: true
      namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: ingress-system
      podSelector:
        matchLabels:
          app.kubernetes.io/name: ingress-controller
    prometheus:
      enabled: true
      namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: monitoring
      podSelector:
        matchLabels:
          app.kubernetes.io/name: prometheus
    management:
      enabled: true
      namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: management
      podSelector:
        matchLabels:
          app.kubernetes.io/name: management-gateway
  egress:
    dns:
      enabled: true
      namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    otlp:
      enabled: true
      peers:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: observability
          podSelector:
            matchLabels:
              app.kubernetes.io/name: otel-collector
      ports:
        - 4318
        - 4319
