[package]
name = "github_webhook_exporter"
version = "0.1.0"
edition = "2021"
authors = ["Peter Grace <pete.grace@gmail.com>"]

[dependencies]
anyhow = "1"
axum = { version = "0.8", default-features = false, features = ["http1", "json", "tokio", "tracing"] }
base64 = "0.22"
prometheus-client = { version = "0.25.0", default-features = false }
secrecy = "0.10"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1"
thiserror = "2.0.6"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3", default-features = false, features = ["fmt", "env-filter"] }

[dev-dependencies]
tokio = { version = "1", features = ["io-util", "time"] }
tower = { version = "0.5", features = ["util"] }
