apiVersion: v1
kind: Service
metadata:
  name: {{ include "github-webhook-exporter.fullname" . }}
  labels:
    {{- include "github-webhook-exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "github-webhook-exporter.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: http
